### PR TITLE
update babel@7 and babelify@10

### PR DESCRIPTION
**Pull request by francoiscote**
I could not install this package on a project built on babel@7. This should fix it.

### CODE REVIEW

**Comment by stevenvachon** [comment]
I think @babel/plugin-transform-new-target is built into 7.x and may not need to be explicitly listed.

**Comment by francoiscote** [comment]
You are right. I removed the plugin and the reference to it in `babelify`'s options

**Comment by francoiscote** [comment]
CI failed on node8 due to a timeout. I tried it locally and it worked fine. 🤔

**Comment by stevenvachon** [comment]
I ran a retest and it passed. However, `babel-plugin-transform-builtin-extend` isn't listed as a [dependency of `@babel/preset-env`](
https://www.npmjs.com/package/@babel/preset-env?activeTab=dependencies).

Also, please remove yarn.lock

**Comment by francoiscote** [comment]
`plugin-transform-builtin-extend` does not exist for babel@7, because it was a bugfix that is now included into babel.

https://twitter.com/left_pad/status/940723982638157829

**Comment by stevenvachon** [comment]
Thanks!

**Pull request merged**
